# Generated by Django 5.0.1 on 2024-02-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_contact_contact_info_partner_testmonial_working_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
