# Generated by Django 5.0.1 on 2024-02-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_rename_authon_testmonial_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmonial',
            old_name='description',
            new_name='description1',
        ),
    ]
