# Generated by Django 5.0.1 on 2024-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_rename_description_testmonial_description1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon1', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
