# Generated by Django 5.0.1 on 2024-02-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolioImage/')),
                ('title', models.CharField(max_length=40)),
                ('link1', models.URLField(blank=True, null=True)),
                ('link2', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
    ]
