# Generated by Django 5.0.1 on 2024-02-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testmonialImage/'),
        ),
    ]
